"""本子插件的命令声明；matcher 与帮助目录共享同一数据源。"""

from ..command_definition import CommandDefinition, command_map  # noqa: TID252

COMMAND_DEFINITIONS = (
    CommandDefinition(
        name="跑团",
        aliases=("开团", "TRPG"),
        description="开设跑团房间（房主自动报名）",
        feature="rpg",
        scope="group",
        display_level="entry",
        namespace_path=("跑团",),
    ),
    CommandDefinition(
        name="模组列表",
        aliases=("模组",),
        description="列出可选剧本模组",
        feature="rpg",
        scope="group",
        display_level="entry",
        namespace_path=("跑团", "模组列表"),
    ),
    CommandDefinition(
        name="跑团帮助",
        aliases=("TRPG帮助",),
        description="按当前阶段查看新手玩法引导",
        feature="rpg",
        display_level="entry",
        namespace_path=("跑团", "帮助"),
    ),
    CommandDefinition(
        name="选择模组",
        aliases=("选模组",),
        description="选定剧本（房主/群管/超管）",
        feature="rpg",
        scope="group",
        permission="room_host_or_admin",
        display_level="lobby",
        namespace_path=("跑团", "选择模组"),
    ),
    CommandDefinition(
        name="报名",
        aliases=("上车", "加一"),
        description="报名加入跑团",
        feature="rpg",
        scope="group",
        display_level="lobby",
        namespace_path=("跑团", "报名"),
        context_game="rpg",
    ),
    CommandDefinition(
        name="退报名",
        aliases=("下车",),
        description="退出跑团报名",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="lobby",
        namespace_path=("跑团", "退报名"),
        context_game="rpg",
    ),
    CommandDefinition(
        name="查看报名",
        aliases=("报名情况",),
        description="查看报名名单",
        feature="rpg",
        scope="group",
        display_level="lobby",
        namespace_path=("跑团", "查看报名"),
        context_game="rpg",
    ),
    CommandDefinition(
        name="开始游戏",
        aliases=("发车",),
        description="开始游戏（房主/群管/超管）",
        feature="rpg",
        scope="group",
        permission="room_host_or_admin",
        display_level="lobby",
        namespace_path=("跑团", "开始游戏"),
        context_game="rpg",
    ),
    CommandDefinition(
        name="局面",
        aliases=("当前局面", "跑团状态"),
        description="查看公开局面并私聊接收个人状态",
        feature="rpg",
        scope="group",
        display_level="active",
        namespace_path=("跑团", "局面"),
        context_game="rpg",
    ),
    CommandDefinition(
        name="状态",
        aliases=("我的状态",),
        description="查看自己的 HP/SAN/属性",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="active",
        operation_support=True,
        namespace_path=("跑团", "状态"),
    ),
    CommandDefinition(
        name="技能",
        aliases=("技能列表",),
        description="查看自己的技能值",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="active",
        namespace_path=("跑团", "技能"),
    ),
    CommandDefinition(
        name="线索",
        aliases=("已发现线索",),
        description="查看公共线索和自己的调查手记",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="active",
        namespace_path=("跑团", "线索"),
    ),
    CommandDefinition(
        name="线索板",
        aliases=("证据板",),
        description="查看团队公开线索和联合推理进度",
        feature="rpg",
        scope="group",
        display_level="active",
        namespace_path=("跑团", "线索板"),
    ),
    CommandDefinition(
        name="时间",
        aliases=("时辰",),
        description="查看游戏内时钟",
        feature="rpg",
        scope="group",
        display_level="active",
        namespace_path=("跑团", "时间"),
    ),
    CommandDefinition(
        name="结束游戏",
        aliases=("解散团",),
        description="结束跑团（房主/群管/超管）",
        feature="rpg",
        scope="group",
        permission="room_host_or_admin",
        display_level="contextual",
        namespace_path=("跑团", "结束游戏"),
        context_game="rpg",
    ),
    CommandDefinition(
        name="检定",
        aliases=("rc",),
        description="执行显式技能检定",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "检定"),
    ),
    CommandDefinition(
        name="攻击",
        aliases=("打",),
        description="攻击场景中的怪物或 NPC",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "攻击"),
    ),
    CommandDefinition(
        name="前往",
        aliases=("去",),
        description="经出口切换场景",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "前往"),
    ),
    CommandDefinition(
        name="等待",
        aliases=("休息",),
        description="原地等待指定分钟数",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "等待"),
    ),
    CommandDefinition(
        name="协助",
        aliases=("帮忙",),
        description="协助同场景调查员的下一次检定",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "协助"),
    ),
    CommandDefinition(
        name="分享线索",
        aliases=("公开线索",),
        description="把自己的个人线索公开给队伍",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "分享线索"),
    ),
    CommandDefinition(
        name="推理",
        aliases=("联合推理",),
        description="组合线索发起团队推理",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "推理"),
    ),
    CommandDefinition(
        name="赞成推理",
        description="确认当前团队推理提案",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "赞成推理"),
    ),
    CommandDefinition(
        name="撤回推理",
        description="撤回自己发起的团队推理提案",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "撤回推理"),
    ),
    CommandDefinition(
        name="跳过",
        aliases=("结束行动",),
        description="结束本探索轮或当前战斗行动",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "跳过"),
    ),
    CommandDefinition(
        name="分享情报",
        aliases=("公开情报",),
        description="公开自己从 NPC 获得的个人情报",
        feature="rpg",
        scope="group",
        permission="player",
        display_level="contextual",
        namespace_path=("跑团", "分享情报"),
    ),
    CommandDefinition(
        name="跳过引导",
        description="停止自动新手提示",
        feature="rpg",
        display_level="advanced",
        namespace_path=("跑团", "跳过引导"),
    ),
    CommandDefinition(
        name="重新引导",
        description="重置当前版本的新手引导状态",
        feature="rpg",
        display_level="advanced",
        namespace_path=("跑团", "重新引导"),
    ),
)

COMMAND_BY_NAME = command_map(COMMAND_DEFINITIONS)
