"""Golden vectors for the pinned pure-Python Fanqie App signer."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast

import pytest

if TYPE_CHECKING:
    from types import ModuleType

_MODULE_PATH = (
    Path(__file__).parents[1]
    / "src"
    / "plugins"
    / "yawn_core"
    / "yawn_fanqie"
    / "app_signer.py"
)
_MODULE_NAME = "test_yawn_fanqie_app_signer"
_LOAD_ERROR = "cannot load Fanqie App signer"


def _load_signer() -> ModuleType:
    spec = importlib.util.spec_from_file_location(_MODULE_NAME, _MODULE_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(_LOAD_ERROR)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


signer = _load_signer()
sign_request = cast("Any", signer.sign_request)
SignerDeviceProfile = cast("Any", signer.SignerDeviceProfile)
SignerNonces = cast("Any", signer.SignerNonces)

_URL = (
    "https://api5-normal-sinfonlinea.fqnovel.com/"
    "reading/reader/batch_full/v:version/?"
    "z=last&empty=&escaped=%2f%2F&repeat=one&repeat=two&"
    "unicode=%E4%B8%AD#ignored=fragment"
)
_BODY = b'{"item_ids":["7592456826415743550"],"flag":true}'
_NOW_MS = 1_785_465_602_789
_NONCES = SignerNonces(
    helios=0x0123_4567,
    medusa_root=0x1234_5678,
    medusa_payload=0x2345_6789,
    medusa_seed=0x3456_789A,
)
_MEDUSA = (
    "7wpsasdBI6Cjf2Ep1b/CRshnoDyJZwEC8MRP2njWNhGBHhhxXuT+rf6cdVRmDD5L7Bcn"
    "IdbgyqRCqJM1ldszG8m3LRMG/kgqihaunvx1TgMan0WX4hv3pLWRPhT8JFOQTkLiKiLi58r"
    "T9wEIPuiPJC/x5blNL6cZWvO3b5kAz6fUyGVbipzcjF6uFYVghMqqdfJ1c0gtCsuXVh0U0"
    "OcJarMAgCsZP2R5glMkR7CH82FSOiYXK7Az2zo/qcoVqgaH+R9A6aYtHDPEaOnYaQpAUEis"
    "Jv4JCBBLsSaT4KPae115KuAtc0/y2yua9KG9xvFMCWcDQpj9SpEC7YneZoHUAMOicednSfq"
    "voyfsd4G/AX2j4Ukw15fpOrTkh7EA/4NM5W82HmEDJQ3lmuqalwDXRIAhy5GOlxRZsf6UtM"
    "5T50srsn6JyGg9Vr9gaydIM1QjtghcRg4DtHIcCDyq2vRDzwMf9LZqEWnh4H1KhzhdGUIrQ"
    "89T/VlzqQ6Wip1nLJvakVh8BOgVu/2kgPNUqNyR59A39bNKQphUAuV5nzVppawg2josMOn/"
    "Dx05O2qW9reX2dn2rlmZc+yDFn+3tnpjbHdJi48v9onPf2zaUuGS2KhKfLS0+shqNefn1l"
    "yF2BLfmPjIIKkB2poSIOeIj7VDRO/ozhhbc4+H06KwyOvEupPms/89DymdPnPS/iqO3qRe"
    "iG7Hy/D1S1lb5fLnSJqMuYjMRM/2/7lL4ByjDzy6Og7wBltRUuXyTcZ1fb9nkdKxiddxle"
    "WHl/B9pOzOQa/n+PTlRTV8rzKfhrUU3TqAQEdHdAB350/5tmO5ZFlCRU5+eLLKfjGs2HPta"
    "b/O3RBBzCaOozEfvWYbhBkEtBi4Pz3ZBjmQ/xKJVmTcakXt8GUxMxyAKYYnFEXUtoQpAllk"
    "ISseqKasIL2LYAqOYOkgTUVjiAr//deb//3Ws0Uj"
)


def test_sign_request_matches_pinned_rust_oracle() -> None:
    """Vector generated by fanqie-rs 906c6fd with a temporary Rust unit test."""

    assert sign_request(_URL, _BODY, now_ms=_NOW_MS, nonces=_NONCES) == {
        "X-Argus": "6gpsag==",
        "X-Gorgon": "8404b01e2801f91d7c5178c514686b7ce19b16528243dd39d779",
        "X-Helios": "Z0UjAW9fLJykDt8DAO0/iTXmQTLasdqEm5uQjtr4AkmVS73X",
        "X-Khronos": "1785465578",
        "X-Ladon": "AAAAAA==",
        "X-Medusa": _MEDUSA,
        "x-ss-stub": "2F3A2D7858E1F2B66A4FFBC14ECB94BE",
    }


def test_sign_request_preserves_raw_query_bytes_and_ignores_fragment() -> None:
    expected = sign_request(_URL, _BODY, now_ms=_NOW_MS, nonces=_NONCES)

    different_fragment = _URL.replace("#ignored=fragment", "#another-fragment")
    normalized_escape = _URL.replace("%2f%2F", "%2F%2F")

    assert (
        sign_request(
            different_fragment,
            _BODY,
            now_ms=_NOW_MS,
            nonces=_NONCES,
        )
        == expected
    )
    assert (
        sign_request(
            normalized_escape,
            _BODY,
            now_ms=_NOW_MS,
            nonces=_NONCES,
        )["X-Gorgon"]
        != expected["X-Gorgon"]
    )


def test_sign_request_parameterizes_all_device_identifiers() -> None:
    default_headers = sign_request(_URL, None, now_ms=_NOW_MS, nonces=_NONCES)
    custom_headers = sign_request(
        _URL,
        None,
        now_ms=_NOW_MS,
        nonces=_NONCES,
        device_profile=SignerDeviceProfile(
            device_id="1000000000000001",
            helios_device_id="200000001",
            aid="9999",
        ),
    )

    assert "x-ss-stub" not in default_headers
    assert custom_headers["X-Helios"] != default_headers["X-Helios"]
    assert custom_headers["X-Medusa"] != default_headers["X-Medusa"]


@pytest.mark.parametrize("nonces", [(), (1, 2, 3), (1, 2, 3, -1)])
def test_sign_request_rejects_invalid_nonce_sets(nonces: tuple[int, ...]) -> None:
    with pytest.raises(ValueError):
        sign_request(_URL, now_ms=_NOW_MS, nonces=nonces)
