"""add werewolf tables

迁移 ID: 155f2713d519
父迁移: 
创建时间: 2026-07-30 23:45:04.840195

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '155f2713d519'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('yawn_werewolf',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yawn_werewolf_werewolfgame',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('host_user_id', sa.BigInteger(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('winner_faction', sa.String(length=8), nullable=True),
    sa.Column('end_round', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_werewolf_werewolfgame')),
    info={'bind_key': 'yawn_werewolf'}
    )
    with op.batch_alter_table('yawn_werewolf_werewolfgame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yawn_werewolf_werewolfgame_group_id'), ['group_id'], unique=False)

    op.create_table('yawn_werewolf_werewolfplayer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('faction', sa.String(length=8), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('is_sheriff', sa.Boolean(), nullable=False),
    sa.Column('death_round', sa.Integer(), nullable=True),
    sa.Column('death_cause', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['yawn_werewolf_werewolfgame.id'], name=op.f('fk_yawn_werewolf_werewolfplayer_game_id_yawn_werewolf_werewolfgame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_werewolf_werewolfplayer')),
    info={'bind_key': 'yawn_werewolf'}
    )
    with op.batch_alter_table('yawn_werewolf_werewolfplayer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yawn_werewolf_werewolfplayer_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_yawn_werewolf_werewolfplayer_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_werewolf_werewolfplayer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_werewolf_werewolfplayer_user_id'))
        batch_op.drop_index(batch_op.f('ix_yawn_werewolf_werewolfplayer_game_id'))

    op.drop_table('yawn_werewolf_werewolfplayer')
    with op.batch_alter_table('yawn_werewolf_werewolfgame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_werewolf_werewolfgame_group_id'))

    op.drop_table('yawn_werewolf_werewolfgame')
    # ### end Alembic commands ###
