"""add checkin tables

迁移 ID: c70afa832d5b
父迁移: 
创建时间: 2026-07-28 22:29:15.751482

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c70afa832d5b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('yawn_core',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yawn_core_checkinrecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_core_checkinrecord')),
    sa.UniqueConstraint('group_id', 'user_id', 'checkin_date', name='uq_checkin_record_once_per_day'),
    info={'bind_key': 'yawn_core'}
    )
    op.create_table('yawn_core_checkinuser',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('last_checkin_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_yawn_core_checkinuser')),
    info={'bind_key': 'yawn_core'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yawn_core_checkinuser')
    op.drop_table('yawn_core_checkinrecord')
    # ### end Alembic commands ###
