"""add checkin tables

迁移 ID: f2c701c101ef
父迁移: f62b2de6aa8a
创建时间: 2026-07-30 13:56:31.212521

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f2c701c101ef'
down_revision: str | Sequence[str] | None = 'f62b2de6aa8a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yawn_core_chatsession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_core_chatsession')),
    info={'bind_key': 'yawn_core'}
    )
    with op.batch_alter_table('yawn_core_chatsession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yawn_core_chatsession_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_yawn_core_chatsession_user_id'), ['user_id'], unique=False)

    op.create_table('yawn_core_chatmessage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['yawn_core_chatsession.id'], name=op.f('fk_yawn_core_chatmessage_session_id_yawn_core_chatsession'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_core_chatmessage')),
    info={'bind_key': 'yawn_core'}
    )
    with op.batch_alter_table('yawn_core_chatmessage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yawn_core_chatmessage_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_core_chatmessage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_core_chatmessage_session_id'))

    op.drop_table('yawn_core_chatmessage')
    with op.batch_alter_table('yawn_core_chatsession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_core_chatsession_user_id'))
        batch_op.drop_index(batch_op.f('ix_yawn_core_chatsession_group_id'))

    op.drop_table('yawn_core_chatsession')
    # ### end Alembic commands ###
