#!/bin/sh
set -efu

set -- ${SSH_ORIGINAL_COMMAND:-}
case "$#" in
    4) ;;
    5) [ "$5" = github-token-stdin ] || exit 2 ;;
    *) exit 2 ;;
esac
[ "$1" = /opt/yawnbot/bin/deploy-release ] || exit 2

exec "$@"
