#!/bin/sh
set -efu

set -- ${SSH_ORIGINAL_COMMAND:-}
case "${1:-}" in
    /opt/yawnbot/bin/deploy-release)
        case "$#" in
            4) ;;
            5)
                case "$5" in
                    github-token-stdin|registry-token-stdin) ;;
                    *) exit 2 ;;
                esac
                ;;
            *) exit 2 ;;
        esac
        ;;
    /opt/yawnbot/bin/sync-control-plane)
        [ "$#" -eq 2 ] || exit 2
        printf '%s\n' "$2" | grep -Eq '^[0-9a-f]{64}$' || exit 2
        ;;
    *) exit 2 ;;
esac

exec /bin/sh "$@"
