"""add is_ai to werewolf player

迁移 ID: cc9ace87b0ea
父迁移: 
创建时间: 2026-07-31 10:28:23.105592

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cc9ace87b0ea'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_werewolf_werewolfplayer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ai', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_werewolf_werewolfplayer', schema=None) as batch_op:
        batch_op.drop_column('is_ai')

    # ### end Alembic commands ###
