"""add scheduled reminders

迁移 ID: ea3af2a76220
父迁移: d853bca98b7f
创建时间: 2026-08-12 16:33:08.928045

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ea3af2a76220'
down_revision: str | Sequence[str] | None = 'd853bca98b7f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yawn_core_scheduledreminder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('message_segments', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['yawn_core_botgroup.group_id'], name=op.f('fk_yawn_core_scheduledreminder_group_id_yawn_core_botgroup'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_core_scheduledreminder')),
    info={'bind_key': 'yawn_core'}
    )
    with op.batch_alter_table('yawn_core_scheduledreminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yawn_core_scheduledreminder_creator_user_id'), ['creator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_yawn_core_scheduledreminder_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_core_scheduledreminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_core_scheduledreminder_group_id'))
        batch_op.drop_index(batch_op.f('ix_yawn_core_scheduledreminder_creator_user_id'))

    op.drop_table('yawn_core_scheduledreminder')
    # ### end Alembic commands ###
