"""werewolf game board column

迁移 ID: 33d3f5e9af32
父迁移: cc9ace87b0ea
创建时间: 2026-08-01 01:18:08.567664

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


revision: str = "33d3f5e9af32"
down_revision: str | Sequence[str] | None = "cc9ace87b0ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("yawn_werewolf_werewolfgame", schema=None) as batch_op:
        batch_op.add_column(sa.Column("board", sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("yawn_werewolf_werewolfgame", schema=None) as batch_op:
        batch_op.drop_column("board")

    # ### end Alembic commands ###
