"""werewolf game board column

迁移 ID: 33d3f5e9af32
父迁移: 92bdea806856
创建时间: 2026-08-01 01:18:08.567664

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '33d3f5e9af32'
down_revision: str | Sequence[str] | None = '92bdea806856'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_rpg_rpgplayer', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('yawn_werewolf_werewolfgame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_werewolf_werewolfgame', schema=None) as batch_op:
        batch_op.drop_column('board')

    with op.batch_alter_table('yawn_rpg_rpgplayer', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
