"""rpg

迁移 ID: 4d4511a9af13
父迁移: f4b6e8d2a901
创建时间: 2026-08-14 00:21:09.717516

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4d4511a9af13'
down_revision: str | Sequence[str] | None = 'f4b6e8d2a901'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_core_scheduledreminder', schema=None) as batch_op:
        batch_op.alter_column('schedule_type',
               existing_type=sa.VARCHAR(length=16),
               server_default='recurring',
               existing_nullable=False)

    with op.batch_alter_table('yawn_fanqie_fanqiebook', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_yawn_fanqie_fanqiebook_book_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_yawn_fanqie_fanqiebook_book_id'))
        batch_op.create_index(batch_op.f('ix_yawn_fanqie_fanqiebook_book_id'), ['book_id'], unique=True)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_fanqie_fanqiebook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_fanqie_fanqiebook_book_id'))
        batch_op.create_index(batch_op.f('ix_yawn_fanqie_fanqiebook_book_id'), ['book_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_yawn_fanqie_fanqiebook_book_id'), ['book_id'])

    with op.batch_alter_table('yawn_core_scheduledreminder', schema=None) as batch_op:
        batch_op.alter_column('schedule_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###
