"""rpg

迁移 ID: d853bca98b7f
父迁移: 
创建时间: 2026-08-12 14:58:59.945009

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd853bca98b7f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yawn_rpg_rpggame',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('host_user_id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('module_name', sa.String(length=64), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('ending_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_rpg_rpggame')),
    info={'bind_key': 'yawn_rpg'}
    )
    with op.batch_alter_table('yawn_rpg_rpggame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yawn_rpg_rpggame_group_id'), ['group_id'], unique=False)

    op.create_table('yawn_rpg_rpgplayer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('char_name', sa.String(length=32), nullable=False),
    sa.Column('start_hp', sa.Integer(), nullable=False),
    sa.Column('start_san', sa.Integer(), nullable=False),
    sa.Column('final_hp', sa.Integer(), nullable=True),
    sa.Column('final_san', sa.Integer(), nullable=True),
    sa.Column('is_incapped', sa.Boolean(), nullable=False),
    sa.Column('survived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['yawn_rpg_rpggame.id'], name=op.f('fk_yawn_rpg_rpgplayer_game_id_yawn_rpg_rpggame'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yawn_rpg_rpgplayer')),
    info={'bind_key': 'yawn_rpg'}
    )
    with op.batch_alter_table('yawn_rpg_rpgplayer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yawn_rpg_rpgplayer_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_yawn_rpg_rpgplayer_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_rpg_rpgplayer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_rpg_rpgplayer_user_id'))
        batch_op.drop_index(batch_op.f('ix_yawn_rpg_rpgplayer_game_id'))

    op.drop_table('yawn_rpg_rpgplayer')
    with op.batch_alter_table('yawn_rpg_rpggame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yawn_rpg_rpggame_group_id'))

    op.drop_table('yawn_rpg_rpggame')
    # ### end Alembic commands ###
