"""YawnBot 狼人杀子插件：群聊狼人杀（预女猎白 / 预女猎白混 / 禁言骑士 / 禁票骑士）。

作为 yawn_core 的可选子插件加载（父插件不硬依赖本包）：
群内报名匹配，夜间私聊下达行动，群禁言控制发言秩序，
全部阶段带超时托管。命令元数据由父插件 help_panel 扫描。
"""

from nonebot import get_plugin_config, logger
from nonebot.plugin import PluginMetadata

from . import commands, models  # noqa: F401
from .config import Config

__plugin_meta__ = PluginMetadata(
    name="狼人杀",
    description="群聊狼人杀（预女猎白/预女猎白混/禁言骑士/禁票骑士）：群内报名、私聊行动、禁言控场",
    usage="发送 /狼人杀 开房，/板子 切换板子，/报名 加入，夜间按私聊提示行动",
    config=Config,
    extra={
        "commands": [
            {
                "name": "狼人杀",
                "aliases": ["开狼", "来把狼人杀"],
                "description": "开设狼人杀房间（房主自动报名）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "报名",
                "aliases": ["上车", "加一"],
                "description": "报名加入狼人杀",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "退报名",
                "aliases": ["下车"],
                "description": "退出狼人杀报名",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "查看报名",
                "aliases": ["报名情况"],
                "description": "查看报名名单",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "狼人状态",
                "aliases": ["狼局状态", "狼人进度"],
                "description": "查看当前公开进度（不显示身份和夜间行动）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "板子",
                "aliases": ["选板子", "换板子"],
                "description": "查看可选板子；切换板子（板子 名称，房主/群管/超管）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "添加AI",
                "aliases": ["加AI", "补人"],
                "description": "报名阶段添加 AI 玩家（添加AI N，房主/群管/超管）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "移除AI",
                "aliases": ["减AI"],
                "description": "报名阶段移除 AI 玩家（移除AI N，房主/群管/超管）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "开始游戏",
                "aliases": ["发车"],
                "description": "开始游戏（房主/群管/超管）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "结束游戏",
                "aliases": ["解散狼局"],
                "description": "结束对局；无对局时恢复群禁言（房主/群管/超管）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "战绩",
                "aliases": ["狼人战绩"],
                "description": "查看狼人杀胜率（群管/超管可 @ 他人）",
                "feature": "werewolf",
                "scope": "all",
                "superuser": False,
            },
            {
                "name": "选身份",
                "aliases": ["想要"],
                "description": "报名阶段请求期望身份（私聊，选身份 身份名；"
                "多人同选发牌时按份数随机分配）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "取消选身份",
                "aliases": ["不选了"],
                "description": "取消报名阶段的身份请求（私聊）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "身份",
                "aliases": ["重发身份卡"],
                "description": "私聊补发自己的身份卡",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "认主",
                "aliases": ["选主"],
                "description": "混血儿首夜选择主人（私聊，认主N）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "禁言",
                "aliases": ["禁票"],
                "description": "长老夜间选择禁言或禁票目标（私聊，禁言N）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "刀",
                "aliases": ["狼刀"],
                "description": "夜晚狼人击杀（私聊，刀N）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "查验",
                "aliases": ["验"],
                "description": "夜晚预言家查验（私聊，查验N）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "救",
                "aliases": [],
                "description": "夜晚女巫救人（私聊）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "毒",
                "aliases": [],
                "description": "夜晚女巫毒人（私聊，毒N）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "开枪",
                "aliases": ["带"],
                "description": "猎人开枪带走玩家（私聊，开枪N）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "不开枪",
                "aliases": ["压枪"],
                "description": "猎人放弃开枪（私聊）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "认主",
                "aliases": ["选主"],
                "description": "首夜混血儿选择主人"
                "（私聊直接回复 认主N，自由文本无需斜杠）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "禁言",
                "aliases": ["禁票"],
                "description": "夜晚禁言长老禁言/禁票"
                "（私聊直接回复 禁言N / 禁票N，自由文本；过=放弃）",
                "feature": "werewolf",
                "scope": "private",
                "superuser": False,
            },
            {
                "name": "上警",
                "aliases": ["竞选"],
                "description": "报名竞选警长",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "退水",
                "aliases": [],
                "description": "退出警长竞选",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "排序",
                "aliases": [],
                "description": "警长决定发言顺序（排序 N 顺|逆）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "移交警徽",
                "aliases": [],
                "description": "死亡警长移交警徽（移交警徽 N）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "撕警徽",
                "aliases": [],
                "description": "死亡警长撕掉警徽",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "自爆",
                "aliases": [],
                "description": "狼人白天自爆，立即进入夜晚",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "决斗",
                "aliases": [],
                "description": "骑士发言阶段翻牌决斗（决斗 N）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "投票",
                "aliases": ["票"],
                "description": "投票（警长/放逐/PK，投票 N）",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "弃票",
                "aliases": [],
                "description": "放弃投票",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
            {
                "name": "过",
                "aliases": [],
                "description": "提前结束自己的发言/遗言",
                "feature": "werewolf",
                "scope": "group",
                "superuser": False,
            },
        ],
    },
)

config = get_plugin_config(Config)

logger.info("狼人杀子插件已加载")
