"""add checkin tables

迁移 ID: b15555e176e4
父迁移: c70afa832d5b
创建时间: 2026-07-29 03:35:15.006558

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b15555e176e4'
down_revision: str | Sequence[str] | None = 'c70afa832d5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yawn_core_botgroup',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_yawn_core_botgroup')),
    info={'bind_key': 'yawn_core'}
    )
    op.create_table('yawn_core_botuser',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('first_interaction_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('affinity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_yawn_core_botuser')),
    info={'bind_key': 'yawn_core'}
    )
    op.create_table('yawn_core_usergroup',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('group_nickname', sa.String(length=255), nullable=True),
    sa.Column('group_affinity', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['yawn_core_botgroup.group_id'], name=op.f('fk_yawn_core_usergroup_group_id_yawn_core_botgroup'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['yawn_core_botuser.user_id'], name=op.f('fk_yawn_core_usergroup_user_id_yawn_core_botuser'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_yawn_core_usergroup')),
    info={'bind_key': 'yawn_core'}
    )
    with op.batch_alter_table('yawn_core_checkinrecord', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_checkin_record_user_group', 'yawn_core_usergroup', ['group_id', 'user_id'], ['group_id', 'user_id'], ondelete='CASCADE')

    with op.batch_alter_table('yawn_core_checkinuser', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_checkin_user_user_group', 'yawn_core_usergroup', ['group_id', 'user_id'], ['group_id', 'user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yawn_core_checkinuser', schema=None) as batch_op:
        batch_op.drop_constraint('fk_checkin_user_user_group', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('yawn_core_checkinrecord', schema=None) as batch_op:
        batch_op.drop_constraint('fk_checkin_record_user_group', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('yawn_core_usergroup')
    op.drop_table('yawn_core_botuser')
    op.drop_table('yawn_core_botgroup')
    # ### end Alembic commands ###
