"""add checkin tables

迁移 ID: f62b2de6aa8a
父迁移: 53782ad40fab
创建时间: 2026-07-30 11:14:49.502877

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f62b2de6aa8a'
down_revision: str | Sequence[str] | None = '53782ad40fab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yawn_core_globaluserfeature',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['yawn_core_botuser.user_id'], name='fk_global_user_feature_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'feature', name=op.f('pk_yawn_core_globaluserfeature')),
    info={'bind_key': 'yawn_core'}
    )
    op.create_table('yawn_core_groupfeature',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['yawn_core_botgroup.group_id'], name='fk_group_feature_group', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'feature', name=op.f('pk_yawn_core_groupfeature')),
    info={'bind_key': 'yawn_core'}
    )
    op.create_table('yawn_core_userfeature',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id', 'user_id'], ['yawn_core_usergroup.group_id', 'yawn_core_usergroup.user_id'], name='fk_user_feature_user_group', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', 'feature', name=op.f('pk_yawn_core_userfeature')),
    info={'bind_key': 'yawn_core'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yawn_core_userfeature')
    op.drop_table('yawn_core_groupfeature')
    op.drop_table('yawn_core_globaluserfeature')
    # ### end Alembic commands ###
